PANDAS DATA STRUCTURES

1) (Series): series is one-dimensional labeled array capable of holding data of any type (int,str,float,python objects, etc). The axis labels are collectively called index.

pandas.Series(data,index,dtype,copy)

In [14]:
import pandas as pd

# data = array= ['Mango','Apple','banana','pear']
# s=pd.Series(data)
# s=pd.Series(data,index=[100,101,102,103])
# print(s)



data = array = [2,4,5,6,7,8]
for x in data:
  s = x*x+2

print(s)
# print(arr) 
# val = pd.Series(arr)
# val = pd.Series(arr,index=[0,1,3,4,5])

66

# Create Series from dictionaries

In [15]:
data = {'a':0,'b':1,'c':3}
s=pd.Series(data)
print(s)

a    0
b    1
c    3
dtype: int64

#   Accessing Data from Series

In [17]:
s = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print(s[0])    # print using postition
print(s[:3])
print(s[2:4])
print(s['c'])  # print using label

1
a    1
b    2
c    3
dtype: int64
c    3
d    4
dtype: int64
3

**DATA FRAMES - PANDAS**
--> A Data frame is a two-dimensional data structure, i.e, data is aligned in a tabular fashion in rows and columns.


---


--> **features of DataFrame**
- Potentially columns are of different types
- Size - Mutable
- Labeled axes(rows and columns)
- Can perform Arithmetic Operations on rows and columns

In [35]:
# 1)
# data = [1,2,3,4,5]
# d1 = pd.DataFrame(data)
# print(d1)

# 2) Data frame in Two dimensional 

# data2 = [['Alex',10],['Bob',12],['Clarke',13]]
# df = pd.DataFrame(data2,columns=['Name','Age'])
# print(df)


# 3) Take five groceries item where columns has price,item name, item code. 
items = [['0234','Peanut Butter',285],['0543','Pancake',354],['0768','shezwan sauce',249],['0867','Silk',65],['0987','Morziralla cheese',350]]
df2 = pd.DataFrame(items,columns=['Item Code','item','Price'])
print(df2)

  Item Code               item  Price
0      0234      Peanut Butter    285
1      0543            Pancake    354
2      0768      shezwan sauce    249
3      0867               Silk     65
4      0987  Morziralla cheese    350

DATA FRAME from Dictiornary of Series

In [47]:
import pandas as pd

# df = {'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3],index=['e','f','g'])}
# print(df)


itemname = ['Pancake','Peanut butter','Biscuit','Nachos','uncle chips']
itm = pd.Series(itemname)

itemprice = [245,285,50,30,20]
itmprice = pd.Series(itemprice)

itemCode = [2462,765,878,976,143]
Code = pd.Series(itemCode)

frame = {'itemname': itm,'itemprice':itmprice,'itemCode':Code}
df = pd.DataFrame(frame)



# df = df.set_index('itemname')  #it will set as the index of the passed argument
# dloc = df.loc['itemname']
# print(dloc)
print(df)

        itemname  itemprice  itemCode
0        Pancake        245      2462
1  Peanut butter        285       765
2        Biscuit         50       878
3         Nachos         30       976
4    uncle chips         20       143


  How to import data from internet and set into the dataframe